hydra:
  searchpath:
    - file://verl/trainer/config

defaults:
  - ppo_trainer
  - _self_

data:
  gen_batch_size: ${data.train_batch_size}

reward_model:
  reward_kwargs: {}

actor_rollout_ref:
  rollout:
    calculate_log_probs: true

trainer:
  project_name: verl-meta-token
